// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module process_udp_512_2150 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rx_ip2udpFifo_V_data_dout,
        rx_ip2udpFifo_V_data_empty_n,
        rx_ip2udpFifo_V_data_read,
        rx_ip2udpFifo_V_keep_dout,
        rx_ip2udpFifo_V_keep_empty_n,
        rx_ip2udpFifo_V_keep_read,
        rx_ip2udpFifo_V_last_dout,
        rx_ip2udpFifo_V_last_empty_n,
        rx_ip2udpFifo_V_last_read,
        rx_udp2shiftFifo_V_d_din,
        rx_udp2shiftFifo_V_d_full_n,
        rx_udp2shiftFifo_V_d_write,
        rx_udp2shiftFifo_V_k_din,
        rx_udp2shiftFifo_V_k_full_n,
        rx_udp2shiftFifo_V_k_write,
        rx_udp2shiftFifo_V_l_din,
        rx_udp2shiftFifo_V_l_full_n,
        rx_udp2shiftFifo_V_l_write,
        rx_udpMetaFifo_V_din,
        rx_udpMetaFifo_V_full_n,
        rx_udpMetaFifo_V_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [511:0] rx_ip2udpFifo_V_data_dout;
input   rx_ip2udpFifo_V_data_empty_n;
output   rx_ip2udpFifo_V_data_read;
input  [63:0] rx_ip2udpFifo_V_keep_dout;
input   rx_ip2udpFifo_V_keep_empty_n;
output   rx_ip2udpFifo_V_keep_read;
input  [0:0] rx_ip2udpFifo_V_last_dout;
input   rx_ip2udpFifo_V_last_empty_n;
output   rx_ip2udpFifo_V_last_read;
output  [511:0] rx_udp2shiftFifo_V_d_din;
input   rx_udp2shiftFifo_V_d_full_n;
output   rx_udp2shiftFifo_V_d_write;
output  [63:0] rx_udp2shiftFifo_V_k_din;
input   rx_udp2shiftFifo_V_k_full_n;
output   rx_udp2shiftFifo_V_k_write;
output  [0:0] rx_udp2shiftFifo_V_l_din;
input   rx_udp2shiftFifo_V_l_full_n;
output   rx_udp2shiftFifo_V_l_write;
output  [48:0] rx_udpMetaFifo_V_din;
input   rx_udpMetaFifo_V_full_n;
output   rx_udpMetaFifo_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg rx_ip2udpFifo_V_data_read;
reg rx_ip2udpFifo_V_keep_read;
reg rx_ip2udpFifo_V_last_read;
reg rx_udp2shiftFifo_V_d_write;
reg rx_udp2shiftFifo_V_k_write;
reg rx_udp2shiftFifo_V_l_write;
reg rx_udpMetaFifo_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    io_acc_block_signal_op6;
wire   [0:0] tmp_nbreadreq_fu_102_p5;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    io_acc_block_signal_op67;
reg   [0:0] tmp_reg_459;
reg   [0:0] tmp_reg_459_pp0_iter1_reg;
reg   [0:0] or_ln75_reg_482;
reg   [0:0] or_ln75_reg_482_pp0_iter1_reg;
reg   [0:0] tmp_valid_reg_505;
reg    ap_predicate_op67_write_state3;
reg   [0:0] metaWritten_2_load_reg_491;
reg    ap_predicate_op70_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] pu_header_ready;
reg   [15:0] pu_header_idx;
reg   [63:0] pu_header_header_V;
reg   [0:0] metaWritten_2;
reg    rx_ip2udpFifo_V_data_blk_n;
wire    ap_block_pp0_stage0;
reg    rx_ip2udpFifo_V_keep_blk_n;
reg    rx_ip2udpFifo_V_last_blk_n;
reg    rx_udp2shiftFifo_V_d_blk_n;
reg    rx_udp2shiftFifo_V_k_blk_n;
reg    rx_udp2shiftFifo_V_l_blk_n;
reg    rx_udpMetaFifo_V_blk_n;
reg   [511:0] tmp_data_V_reg_463;
reg   [511:0] tmp_data_V_reg_463_pp0_iter1_reg;
reg   [63:0] tmp_keep_V_reg_468;
reg   [63:0] tmp_keep_V_reg_468_pp0_iter1_reg;
reg   [0:0] tmp_last_V_reg_473;
reg   [0:0] tmp_last_V_reg_473_pp0_iter1_reg;
wire   [0:0] or_ln75_fu_323_p2;
wire   [0:0] xor_ln79_fu_329_p2;
reg   [0:0] xor_ln79_reg_486;
wire   [0:0] metaWritten_2_load_load_fu_361_p1;
wire   [7:0] p_Result_128_i_i9_s_fu_369_p4;
reg   [7:0] p_Result_128_i_i9_s_reg_495;
wire   [7:0] p_Result_128_1_i_i_fu_379_p4;
reg   [7:0] p_Result_128_1_i_i_reg_500;
wire   [0:0] tmp_valid_fu_397_p2;
reg   [7:0] p_Result_128_i_i_reg_510;
wire   [7:0] trunc_ln647_fu_413_p1;
reg   [7:0] trunc_ln647_reg_515;
reg   [7:0] p_Result_128_i_i1_reg_520;
reg   [7:0] p_Result_128_1_i_i_2_reg_525;
wire   [0:0] or_ln79_fu_437_p2;
reg    ap_block_pp0_stage0_subdone;
reg   [15:0] ap_phi_mux_phi_ln75_phi_fu_147_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_phi_ln75_reg_144;
wire   [0:0] pu_header_ready_load_load_fu_191_p1;
wire   [15:0] add_ln69_fu_316_p2;
reg   [0:0] ap_phi_mux_write_flag_1_i_i_phi_fu_156_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_write_flag_1_i_i_reg_153;
reg   [0:0] ap_phi_mux_metaWritten_6_flag_1_phi_fu_168_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_metaWritten_6_flag_1_reg_164;
reg   [0:0] ap_phi_reg_pp0_iter1_metaWritten_6_flag_1_reg_164;
wire   [0:0] and_ln79_fu_335_p2;
wire   [15:0] select_ln79_fu_341_p3;
wire   [63:0] p_Result_s_fu_304_p2;
reg    ap_block_pp0_stage0_01001;
wire   [18:0] tmp_38_fu_208_p3;
wire   [25:0] zext_ln414_fu_216_p1;
wire   [0:0] trunc_ln414_fu_226_p1;
wire   [0:0] icmp_ln414_fu_220_p2;
wire   [63:0] st3_fu_230_p3;
wire   [63:0] tmp_V_fu_200_p1;
wire   [63:0] select_ln414_fu_238_p3;
reg   [63:0] tmp_39_fu_246_p4;
wire   [63:0] select_ln414_12_fu_264_p3;
wire   [63:0] select_ln414_13_fu_272_p3;
wire   [63:0] and_ln414_fu_280_p2;
wire   [63:0] xor_ln414_fu_286_p2;
wire   [63:0] select_ln414_11_fu_256_p3;
wire   [63:0] and_ln414_8_fu_292_p2;
wire   [63:0] and_ln414_9_fu_298_p2;
wire   [15:0] dstPort_V_fu_389_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_229;
reg    ap_condition_124;
reg    ap_condition_111;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 pu_header_ready = 1'd0;
#0 pu_header_idx = 16'd0;
#0 pu_header_header_V = 64'd0;
#0 metaWritten_2 = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_111)) begin
        if (((or_ln75_fu_323_p2 == 1'd0) & (tmp_nbreadreq_fu_102_p5 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_metaWritten_6_flag_1_reg_164 <= 1'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_metaWritten_6_flag_1_reg_164 <= ap_phi_reg_pp0_iter0_metaWritten_6_flag_1_reg_164;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_459 == 1'd1) & (or_ln79_fu_437_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        metaWritten_2 <= xor_ln79_reg_486;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_459 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        metaWritten_2_load_reg_491 <= metaWritten_2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_nbreadreq_fu_102_p5 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_ln75_reg_482 <= or_ln75_fu_323_p2;
        tmp_data_V_reg_463 <= rx_ip2udpFifo_V_data_dout;
        tmp_keep_V_reg_468 <= rx_ip2udpFifo_V_keep_dout;
        tmp_last_V_reg_473 <= rx_ip2udpFifo_V_last_dout;
        xor_ln79_reg_486 <= xor_ln79_fu_329_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_ln75_reg_482_pp0_iter1_reg <= or_ln75_reg_482;
        tmp_data_V_reg_463_pp0_iter1_reg <= tmp_data_V_reg_463;
        tmp_keep_V_reg_468_pp0_iter1_reg <= tmp_keep_V_reg_468;
        tmp_last_V_reg_473_pp0_iter1_reg <= tmp_last_V_reg_473;
        tmp_reg_459 <= tmp_nbreadreq_fu_102_p5;
        tmp_reg_459_pp0_iter1_reg <= tmp_reg_459;
    end
end

always @ (posedge ap_clk) begin
    if (((metaWritten_2_load_load_fu_361_p1 == 1'd0) & (or_ln75_reg_482 == 1'd1) & (tmp_reg_459 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Result_128_1_i_i_2_reg_525 <= {{pu_header_header_V[39:32]}};
        p_Result_128_i_i1_reg_520 <= {{pu_header_header_V[47:40]}};
        p_Result_128_i_i_reg_510 <= {{pu_header_header_V[15:8]}};
        trunc_ln647_reg_515 <= trunc_ln647_fu_413_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln75_reg_482 == 1'd1) & (tmp_reg_459 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Result_128_1_i_i_reg_500 <= {{pu_header_header_V[23:16]}};
        p_Result_128_i_i9_s_reg_495 <= {{pu_header_header_V[31:24]}};
        tmp_valid_reg_505 <= tmp_valid_fu_397_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((pu_header_ready_load_load_fu_191_p1 == 1'd0) & (tmp_nbreadreq_fu_102_p5 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pu_header_header_V <= p_Result_s_fu_304_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_nbreadreq_fu_102_p5 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pu_header_idx <= select_ln79_fu_341_p3;
        pu_header_ready <= and_ln79_fu_335_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((metaWritten_2_load_load_fu_361_p1 == 1'd0)) begin
            ap_phi_mux_metaWritten_6_flag_1_phi_fu_168_p6 = 1'd1;
        end else if ((metaWritten_2_load_load_fu_361_p1 == 1'd1)) begin
            ap_phi_mux_metaWritten_6_flag_1_phi_fu_168_p6 = 1'd0;
        end else begin
            ap_phi_mux_metaWritten_6_flag_1_phi_fu_168_p6 = ap_phi_reg_pp0_iter1_metaWritten_6_flag_1_reg_164;
        end
    end else begin
        ap_phi_mux_metaWritten_6_flag_1_phi_fu_168_p6 = ap_phi_reg_pp0_iter1_metaWritten_6_flag_1_reg_164;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_124)) begin
        if ((pu_header_ready_load_load_fu_191_p1 == 1'd0)) begin
            ap_phi_mux_phi_ln75_phi_fu_147_p4 = add_ln69_fu_316_p2;
        end else if ((pu_header_ready_load_load_fu_191_p1 == 1'd1)) begin
            ap_phi_mux_phi_ln75_phi_fu_147_p4 = pu_header_idx;
        end else begin
            ap_phi_mux_phi_ln75_phi_fu_147_p4 = ap_phi_reg_pp0_iter0_phi_ln75_reg_144;
        end
    end else begin
        ap_phi_mux_phi_ln75_phi_fu_147_p4 = ap_phi_reg_pp0_iter0_phi_ln75_reg_144;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_124)) begin
        if ((pu_header_ready_load_load_fu_191_p1 == 1'd0)) begin
            ap_phi_mux_write_flag_1_i_i_phi_fu_156_p4 = 1'd1;
        end else if ((pu_header_ready_load_load_fu_191_p1 == 1'd1)) begin
            ap_phi_mux_write_flag_1_i_i_phi_fu_156_p4 = 1'd0;
        end else begin
            ap_phi_mux_write_flag_1_i_i_phi_fu_156_p4 = ap_phi_reg_pp0_iter0_write_flag_1_i_i_reg_153;
        end
    end else begin
        ap_phi_mux_write_flag_1_i_i_phi_fu_156_p4 = ap_phi_reg_pp0_iter0_write_flag_1_i_i_reg_153;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_nbreadreq_fu_102_p5 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        rx_ip2udpFifo_V_data_blk_n = rx_ip2udpFifo_V_data_empty_n;
    end else begin
        rx_ip2udpFifo_V_data_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_nbreadreq_fu_102_p5 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rx_ip2udpFifo_V_data_read = 1'b1;
    end else begin
        rx_ip2udpFifo_V_data_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_nbreadreq_fu_102_p5 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        rx_ip2udpFifo_V_keep_blk_n = rx_ip2udpFifo_V_keep_empty_n;
    end else begin
        rx_ip2udpFifo_V_keep_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_nbreadreq_fu_102_p5 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rx_ip2udpFifo_V_keep_read = 1'b1;
    end else begin
        rx_ip2udpFifo_V_keep_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (tmp_nbreadreq_fu_102_p5 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        rx_ip2udpFifo_V_last_blk_n = rx_ip2udpFifo_V_last_empty_n;
    end else begin
        rx_ip2udpFifo_V_last_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_nbreadreq_fu_102_p5 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rx_ip2udpFifo_V_last_read = 1'b1;
    end else begin
        rx_ip2udpFifo_V_last_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op67_write_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        rx_udp2shiftFifo_V_d_blk_n = rx_udp2shiftFifo_V_d_full_n;
    end else begin
        rx_udp2shiftFifo_V_d_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op67_write_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rx_udp2shiftFifo_V_d_write = 1'b1;
    end else begin
        rx_udp2shiftFifo_V_d_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op67_write_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        rx_udp2shiftFifo_V_k_blk_n = rx_udp2shiftFifo_V_k_full_n;
    end else begin
        rx_udp2shiftFifo_V_k_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op67_write_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rx_udp2shiftFifo_V_k_write = 1'b1;
    end else begin
        rx_udp2shiftFifo_V_k_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op67_write_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        rx_udp2shiftFifo_V_l_blk_n = rx_udp2shiftFifo_V_l_full_n;
    end else begin
        rx_udp2shiftFifo_V_l_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op67_write_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rx_udp2shiftFifo_V_l_write = 1'b1;
    end else begin
        rx_udp2shiftFifo_V_l_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op70_write_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        rx_udpMetaFifo_V_blk_n = rx_udpMetaFifo_V_full_n;
    end else begin
        rx_udpMetaFifo_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op70_write_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rx_udpMetaFifo_V_write = 1'b1;
    end else begin
        rx_udpMetaFifo_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln69_fu_316_p2 = (16'd1 + pu_header_idx);

assign and_ln414_8_fu_292_p2 = (xor_ln414_fu_286_p2 & pu_header_header_V);

assign and_ln414_9_fu_298_p2 = (select_ln414_11_fu_256_p3 & and_ln414_fu_280_p2);

assign and_ln414_fu_280_p2 = (select_ln414_13_fu_272_p3 & select_ln414_12_fu_264_p3);

assign and_ln79_fu_335_p2 = (xor_ln79_fu_329_p2 & or_ln75_fu_323_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_nbreadreq_fu_102_p5 == 1'd1) & (io_acc_block_signal_op6 == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((rx_udpMetaFifo_V_full_n == 1'b0) & (ap_predicate_op70_write_state3 == 1'b1)) | ((io_acc_block_signal_op67 == 1'b0) & (ap_predicate_op67_write_state3 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_nbreadreq_fu_102_p5 == 1'd1) & (io_acc_block_signal_op6 == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((rx_udpMetaFifo_V_full_n == 1'b0) & (ap_predicate_op70_write_state3 == 1'b1)) | ((io_acc_block_signal_op67 == 1'b0) & (ap_predicate_op67_write_state3 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_nbreadreq_fu_102_p5 == 1'd1) & (io_acc_block_signal_op6 == 1'b0)))) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((rx_udpMetaFifo_V_full_n == 1'b0) & (ap_predicate_op70_write_state3 == 1'b1)) | ((io_acc_block_signal_op67 == 1'b0) & (ap_predicate_op67_write_state3 == 1'b1)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((tmp_nbreadreq_fu_102_p5 == 1'd1) & (io_acc_block_signal_op6 == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (((rx_udpMetaFifo_V_full_n == 1'b0) & (ap_predicate_op70_write_state3 == 1'b1)) | ((io_acc_block_signal_op67 == 1'b0) & (ap_predicate_op67_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_condition_111 = ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_124 = ((tmp_nbreadreq_fu_102_p5 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_229 = ((or_ln75_reg_482 == 1'd1) & (tmp_reg_459 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_metaWritten_6_flag_1_reg_164 = 'bx;

assign ap_phi_reg_pp0_iter0_phi_ln75_reg_144 = 'bx;

assign ap_phi_reg_pp0_iter0_write_flag_1_i_i_reg_153 = 'bx;

always @ (*) begin
    ap_predicate_op67_write_state3 = ((tmp_valid_reg_505 == 1'd1) & (or_ln75_reg_482_pp0_iter1_reg == 1'd1) & (tmp_reg_459_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op70_write_state3 = ((metaWritten_2_load_reg_491 == 1'd0) & (or_ln75_reg_482_pp0_iter1_reg == 1'd1) & (tmp_reg_459_pp0_iter1_reg == 1'd1));
end

assign dstPort_V_fu_389_p3 = {{p_Result_128_1_i_i_fu_379_p4}, {p_Result_128_i_i9_s_fu_369_p4}};

assign icmp_ln414_fu_220_p2 = ((zext_ln414_fu_216_p1 != 26'd0) ? 1'b1 : 1'b0);

assign io_acc_block_signal_op6 = (rx_ip2udpFifo_V_last_empty_n & rx_ip2udpFifo_V_keep_empty_n & rx_ip2udpFifo_V_data_empty_n);

assign io_acc_block_signal_op67 = (rx_udp2shiftFifo_V_l_full_n & rx_udp2shiftFifo_V_k_full_n & rx_udp2shiftFifo_V_d_full_n);

assign metaWritten_2_load_load_fu_361_p1 = metaWritten_2;

assign or_ln75_fu_323_p2 = (pu_header_ready | ap_phi_mux_write_flag_1_i_i_phi_fu_156_p4);

assign or_ln79_fu_437_p2 = (tmp_last_V_reg_473 | ap_phi_mux_metaWritten_6_flag_1_phi_fu_168_p6);

assign p_Result_128_1_i_i_fu_379_p4 = {{pu_header_header_V[23:16]}};

assign p_Result_128_i_i9_s_fu_369_p4 = {{pu_header_header_V[31:24]}};

assign p_Result_s_fu_304_p2 = (and_ln414_9_fu_298_p2 | and_ln414_8_fu_292_p2);

assign pu_header_ready_load_load_fu_191_p1 = pu_header_ready;

assign rx_udp2shiftFifo_V_d_din = tmp_data_V_reg_463_pp0_iter1_reg;

assign rx_udp2shiftFifo_V_k_din = tmp_keep_V_reg_468_pp0_iter1_reg;

assign rx_udp2shiftFifo_V_l_din = tmp_last_V_reg_473_pp0_iter1_reg;

assign rx_udpMetaFifo_V_din = {{{{{{{tmp_valid_reg_505}, {p_Result_128_1_i_i_2_reg_525}}, {p_Result_128_i_i1_reg_520}}, {p_Result_128_1_i_i_reg_500}}, {p_Result_128_i_i9_s_reg_495}}, {trunc_ln647_reg_515}}, {p_Result_128_i_i_reg_510}};

assign select_ln414_11_fu_256_p3 = ((icmp_ln414_fu_220_p2[0:0] === 1'b1) ? tmp_39_fu_246_p4 : tmp_V_fu_200_p1);

assign select_ln414_12_fu_264_p3 = ((icmp_ln414_fu_220_p2[0:0] === 1'b1) ? 64'd9223372036854775808 : 64'd18446744073709551615);

assign select_ln414_13_fu_272_p3 = ((icmp_ln414_fu_220_p2[0:0] === 1'b1) ? 64'd1 : 64'd18446744073709551615);

assign select_ln414_fu_238_p3 = ((icmp_ln414_fu_220_p2[0:0] === 1'b1) ? st3_fu_230_p3 : tmp_V_fu_200_p1);

assign select_ln79_fu_341_p3 = ((rx_ip2udpFifo_V_last_dout[0:0] === 1'b1) ? 16'd0 : ap_phi_mux_phi_ln75_phi_fu_147_p4);

assign st3_fu_230_p3 = {{trunc_ln414_fu_226_p1}, {63'd0}};

assign tmp_38_fu_208_p3 = {{pu_header_idx}, {3'd0}};

integer ap_tvar_int_0;

always @ (select_ln414_fu_238_p3) begin
    for (ap_tvar_int_0 = 64 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 63 - 0) begin
            tmp_39_fu_246_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_39_fu_246_p4[ap_tvar_int_0] = select_ln414_fu_238_p3[63 - ap_tvar_int_0];
        end
    end
end

assign tmp_V_fu_200_p1 = rx_ip2udpFifo_V_data_dout[63:0];

assign tmp_nbreadreq_fu_102_p5 = (rx_ip2udpFifo_V_last_empty_n & rx_ip2udpFifo_V_keep_empty_n & rx_ip2udpFifo_V_data_empty_n);

assign tmp_valid_fu_397_p2 = ((dstPort_V_fu_389_p3 == 16'd4791) ? 1'b1 : 1'b0);

assign trunc_ln414_fu_226_p1 = rx_ip2udpFifo_V_data_dout[0:0];

assign trunc_ln647_fu_413_p1 = pu_header_header_V[7:0];

assign xor_ln414_fu_286_p2 = (64'd18446744073709551615 ^ and_ln414_fu_280_p2);

assign xor_ln79_fu_329_p2 = (rx_ip2udpFifo_V_last_dout ^ 1'd1);

assign zext_ln414_fu_216_p1 = tmp_38_fu_208_p3;

endmodule //process_udp_512_2150
