-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity compute_ipv4_checksu is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ip2checksum_V_data_V_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    ip2checksum_V_data_V_empty_n : IN STD_LOGIC;
    ip2checksum_V_data_V_read : OUT STD_LOGIC;
    ip2checksum_V_keep_V_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    ip2checksum_V_keep_V_empty_n : IN STD_LOGIC;
    ip2checksum_V_keep_V_read : OUT STD_LOGIC;
    ip2checksum_V_last_V_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    ip2checksum_V_last_V_empty_n : IN STD_LOGIC;
    ip2checksum_V_last_V_read : OUT STD_LOGIC;
    tx_ip2crcFifo_V_data_din : OUT STD_LOGIC_VECTOR (511 downto 0);
    tx_ip2crcFifo_V_data_full_n : IN STD_LOGIC;
    tx_ip2crcFifo_V_data_write : OUT STD_LOGIC;
    tx_ip2crcFifo_V_keep_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    tx_ip2crcFifo_V_keep_full_n : IN STD_LOGIC;
    tx_ip2crcFifo_V_keep_write : OUT STD_LOGIC;
    tx_ip2crcFifo_V_last_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    tx_ip2crcFifo_V_last_full_n : IN STD_LOGIC;
    tx_ip2crcFifo_V_last_write : OUT STD_LOGIC );
end;


architecture behav of compute_ipv4_checksu is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_57 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010111";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_87 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000111";
    constant ap_const_lv32_98 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_97 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010111";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal io_acc_block_signal_op5 : STD_LOGIC;
    signal tmp_nbreadreq_fu_126_p5 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal io_acc_block_signal_op91 : STD_LOGIC;
    signal tmp_reg_703 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal cics_firstWord : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal ip2checksum_V_data_V_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ip2checksum_V_keep_V_blk_n : STD_LOGIC;
    signal ip2checksum_V_last_V_blk_n : STD_LOGIC;
    signal tx_ip2crcFifo_V_data_blk_n : STD_LOGIC;
    signal tx_ip2crcFifo_V_keep_blk_n : STD_LOGIC;
    signal tx_ip2crcFifo_V_last_blk_n : STD_LOGIC;
    signal tmp_data_V_66_reg_707 : STD_LOGIC_VECTOR (511 downto 0);
    signal tmp_keep_V_reg_713 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_last_V_reg_718 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln214_1_fu_637_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_1_reg_725 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal or_ln99_fu_693_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln647_fu_183_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_128_i_i_fu_173_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal agg_result_V_0_1_i_i_fu_187_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_128_1_i_fu_209_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_128_i43_i_fu_199_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal agg_result_V_0_1_i_fu_219_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln700_fu_227_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln647_fu_195_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_fu_231_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Result_128_1_i1_fu_251_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_128_i46_i_fu_241_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal agg_result_V_0_1_i1_fu_261_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_128_1_i2_fu_283_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_128_i49_i_fu_273_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal agg_result_V_0_1_i2_fu_293_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln700_2_fu_301_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln647_1_fu_269_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_12_fu_305_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln700_1_fu_237_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_3_fu_311_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln700_13_fu_315_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Result_128_1_i3_fu_335_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_128_i52_i_fu_325_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal agg_result_V_0_1_i3_fu_345_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_128_1_i4_fu_367_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_128_i55_i_fu_357_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal agg_result_V_0_1_i4_fu_377_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_128_1_i5_fu_399_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_128_i58_i_fu_389_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal agg_result_V_0_1_i5_fu_409_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_128_1_i6_fu_431_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_128_i61_i_fu_421_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal agg_result_V_0_1_i6_fu_441_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln700_5_fu_353_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln700_4_fu_321_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln700_6_fu_449_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln647_3_fu_417_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_15_fu_459_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln647_2_fu_385_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_7_fu_465_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln700_16_fu_469_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln700_14_fu_453_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln700_8_fu_475_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln700_17_fu_479_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_Result_128_1_i7_fu_499_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_128_i64_i_fu_489_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal agg_result_V_0_1_i7_fu_509_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_128_1_i8_fu_531_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_128_i67_i_fu_521_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal agg_result_V_0_1_i8_fu_541_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln700_10_fu_549_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln647_4_fu_517_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_18_fu_553_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln700_9_fu_485_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln700_11_fu_559_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln700_19_fu_563_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_s_fu_569_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln214_4_fu_589_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_fu_583_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_5_fu_595_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_7_fu_607_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1503_fu_579_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_9_fu_619_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_8_fu_613_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_10_fu_625_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_6_fu_601_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln214_11_fu_631_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_fu_647_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln647_29_fu_662_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_128_i70_i_fu_652_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal checksum_V_fu_666_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_s_fu_674_p5 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_nbreadreq_fu_126_p5 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln214_1_reg_725 <= add_ln214_1_fu_637_p2;
                tmp_data_V_66_reg_707 <= ip2checksum_V_data_V_dout;
                tmp_keep_V_reg_713 <= ip2checksum_V_keep_V_dout;
                tmp_last_V_reg_718 <= ip2checksum_V_last_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_703 = ap_const_lv1_1) and (or_ln99_fu_693_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                cics_firstWord <= tmp_last_V_reg_718;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_reg_703 <= tmp_nbreadreq_fu_126_p5;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln214_10_fu_625_p2 <= std_logic_vector(unsigned(agg_result_V_0_1_i7_fu_509_p3) + unsigned(add_ln214_9_fu_619_p2));
    add_ln214_11_fu_631_p2 <= std_logic_vector(unsigned(add_ln214_8_fu_613_p2) + unsigned(add_ln214_10_fu_625_p2));
    add_ln214_1_fu_637_p2 <= std_logic_vector(unsigned(add_ln214_6_fu_601_p2) + unsigned(add_ln214_11_fu_631_p2));
    add_ln214_4_fu_589_p2 <= std_logic_vector(unsigned(agg_result_V_0_1_i3_fu_345_p3) + unsigned(agg_result_V_0_1_i2_fu_293_p3));
    add_ln214_5_fu_595_p2 <= std_logic_vector(unsigned(agg_result_V_0_1_i1_fu_261_p3) + unsigned(add_ln214_4_fu_589_p2));
    add_ln214_6_fu_601_p2 <= std_logic_vector(unsigned(add_ln214_fu_583_p2) + unsigned(add_ln214_5_fu_595_p2));
    add_ln214_7_fu_607_p2 <= std_logic_vector(unsigned(agg_result_V_0_1_i6_fu_441_p3) + unsigned(agg_result_V_0_1_i5_fu_409_p3));
    add_ln214_8_fu_613_p2 <= std_logic_vector(unsigned(agg_result_V_0_1_i4_fu_377_p3) + unsigned(add_ln214_7_fu_607_p2));
    add_ln214_9_fu_619_p2 <= std_logic_vector(unsigned(zext_ln1503_fu_579_p1) + unsigned(agg_result_V_0_1_i8_fu_541_p3));
    add_ln214_fu_583_p2 <= std_logic_vector(unsigned(agg_result_V_0_1_i_i_fu_187_p3) + unsigned(agg_result_V_0_1_i_fu_219_p3));
    add_ln700_12_fu_305_p2 <= std_logic_vector(unsigned(zext_ln700_2_fu_301_p1) + unsigned(zext_ln647_1_fu_269_p1));
    add_ln700_13_fu_315_p2 <= std_logic_vector(unsigned(zext_ln700_1_fu_237_p1) + unsigned(zext_ln700_3_fu_311_p1));
    add_ln700_14_fu_453_p2 <= std_logic_vector(unsigned(zext_ln700_5_fu_353_p1) + unsigned(zext_ln700_4_fu_321_p1));
    add_ln700_15_fu_459_p2 <= std_logic_vector(unsigned(zext_ln700_6_fu_449_p1) + unsigned(zext_ln647_3_fu_417_p1));
    add_ln700_16_fu_469_p2 <= std_logic_vector(unsigned(zext_ln647_2_fu_385_p1) + unsigned(zext_ln700_7_fu_465_p1));
    add_ln700_17_fu_479_p2 <= std_logic_vector(unsigned(add_ln700_14_fu_453_p2) + unsigned(zext_ln700_8_fu_475_p1));
    add_ln700_18_fu_553_p2 <= std_logic_vector(unsigned(zext_ln700_10_fu_549_p1) + unsigned(zext_ln647_4_fu_517_p1));
    add_ln700_19_fu_563_p2 <= std_logic_vector(unsigned(zext_ln700_9_fu_485_p1) + unsigned(zext_ln700_11_fu_559_p1));
    add_ln700_fu_231_p2 <= std_logic_vector(unsigned(zext_ln700_fu_227_p1) + unsigned(zext_ln647_fu_195_p1));
    agg_result_V_0_1_i1_fu_261_p3 <= (p_Result_128_1_i1_fu_251_p4 & p_Result_128_i46_i_fu_241_p4);
    agg_result_V_0_1_i2_fu_293_p3 <= (p_Result_128_1_i2_fu_283_p4 & p_Result_128_i49_i_fu_273_p4);
    agg_result_V_0_1_i3_fu_345_p3 <= (p_Result_128_1_i3_fu_335_p4 & p_Result_128_i52_i_fu_325_p4);
    agg_result_V_0_1_i4_fu_377_p3 <= (p_Result_128_1_i4_fu_367_p4 & p_Result_128_i55_i_fu_357_p4);
    agg_result_V_0_1_i5_fu_409_p3 <= (p_Result_128_1_i5_fu_399_p4 & p_Result_128_i58_i_fu_389_p4);
    agg_result_V_0_1_i6_fu_441_p3 <= (p_Result_128_1_i6_fu_431_p4 & p_Result_128_i61_i_fu_421_p4);
    agg_result_V_0_1_i7_fu_509_p3 <= (p_Result_128_1_i7_fu_499_p4 & p_Result_128_i64_i_fu_489_p4);
    agg_result_V_0_1_i8_fu_541_p3 <= (p_Result_128_1_i8_fu_531_p4 & p_Result_128_i67_i_fu_521_p4);
    agg_result_V_0_1_i_fu_219_p3 <= (p_Result_128_1_i_fu_209_p4 & p_Result_128_i43_i_fu_199_p4);
    agg_result_V_0_1_i_i_fu_187_p3 <= (trunc_ln647_fu_183_p1 & p_Result_128_i_i_fu_173_p4);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, io_acc_block_signal_op5, tmp_nbreadreq_fu_126_p5, io_acc_block_signal_op91, tmp_reg_703)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((tmp_reg_703 = ap_const_lv1_1) and (io_acc_block_signal_op91 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_nbreadreq_fu_126_p5 = ap_const_lv1_1) and (io_acc_block_signal_op5 = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, io_acc_block_signal_op5, tmp_nbreadreq_fu_126_p5, io_acc_block_signal_op91, tmp_reg_703)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((tmp_reg_703 = ap_const_lv1_1) and (io_acc_block_signal_op91 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_nbreadreq_fu_126_p5 = ap_const_lv1_1) and (io_acc_block_signal_op5 = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, io_acc_block_signal_op5, tmp_nbreadreq_fu_126_p5, io_acc_block_signal_op91, tmp_reg_703)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((tmp_reg_703 = ap_const_lv1_1) and (io_acc_block_signal_op91 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_nbreadreq_fu_126_p5 = ap_const_lv1_1) and (io_acc_block_signal_op5 = ap_const_logic_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, ap_done_reg, io_acc_block_signal_op5, tmp_nbreadreq_fu_126_p5)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_nbreadreq_fu_126_p5 = ap_const_lv1_1) and (io_acc_block_signal_op5 = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(io_acc_block_signal_op91, tmp_reg_703)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((tmp_reg_703 = ap_const_lv1_1) and (io_acc_block_signal_op91 = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    checksum_V_fu_666_p3 <= (trunc_ln647_29_fu_662_p1 & p_Result_128_i70_i_fu_652_p4);
    io_acc_block_signal_op5 <= (ip2checksum_V_last_V_empty_n and ip2checksum_V_keep_V_empty_n and ip2checksum_V_data_V_empty_n);
    io_acc_block_signal_op91 <= (tx_ip2crcFifo_V_last_full_n and tx_ip2crcFifo_V_keep_full_n and tx_ip2crcFifo_V_data_full_n);

    ip2checksum_V_data_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, ip2checksum_V_data_V_empty_n, tmp_nbreadreq_fu_126_p5, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (tmp_nbreadreq_fu_126_p5 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ip2checksum_V_data_V_blk_n <= ip2checksum_V_data_V_empty_n;
        else 
            ip2checksum_V_data_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ip2checksum_V_data_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_nbreadreq_fu_126_p5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_nbreadreq_fu_126_p5 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ip2checksum_V_data_V_read <= ap_const_logic_1;
        else 
            ip2checksum_V_data_V_read <= ap_const_logic_0;
        end if; 
    end process;


    ip2checksum_V_keep_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, ip2checksum_V_keep_V_empty_n, tmp_nbreadreq_fu_126_p5, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (tmp_nbreadreq_fu_126_p5 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ip2checksum_V_keep_V_blk_n <= ip2checksum_V_keep_V_empty_n;
        else 
            ip2checksum_V_keep_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ip2checksum_V_keep_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_nbreadreq_fu_126_p5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_nbreadreq_fu_126_p5 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ip2checksum_V_keep_V_read <= ap_const_logic_1;
        else 
            ip2checksum_V_keep_V_read <= ap_const_logic_0;
        end if; 
    end process;


    ip2checksum_V_last_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, ip2checksum_V_last_V_empty_n, tmp_nbreadreq_fu_126_p5, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (tmp_nbreadreq_fu_126_p5 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ip2checksum_V_last_V_blk_n <= ip2checksum_V_last_V_empty_n;
        else 
            ip2checksum_V_last_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ip2checksum_V_last_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_nbreadreq_fu_126_p5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_nbreadreq_fu_126_p5 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ip2checksum_V_last_V_read <= ap_const_logic_1;
        else 
            ip2checksum_V_last_V_read <= ap_const_logic_0;
        end if; 
    end process;

    or_ln99_fu_693_p2 <= (tmp_last_V_reg_718 or cics_firstWord);
    p_Result_128_1_i1_fu_251_p4 <= ip2checksum_V_data_V_dout(39 downto 32);
    p_Result_128_1_i2_fu_283_p4 <= ip2checksum_V_data_V_dout(55 downto 48);
    p_Result_128_1_i3_fu_335_p4 <= ip2checksum_V_data_V_dout(71 downto 64);
    p_Result_128_1_i4_fu_367_p4 <= ip2checksum_V_data_V_dout(87 downto 80);
    p_Result_128_1_i5_fu_399_p4 <= ip2checksum_V_data_V_dout(103 downto 96);
    p_Result_128_1_i6_fu_431_p4 <= ip2checksum_V_data_V_dout(119 downto 112);
    p_Result_128_1_i7_fu_499_p4 <= ip2checksum_V_data_V_dout(135 downto 128);
    p_Result_128_1_i8_fu_531_p4 <= ip2checksum_V_data_V_dout(151 downto 144);
    p_Result_128_1_i_fu_209_p4 <= ip2checksum_V_data_V_dout(23 downto 16);
    p_Result_128_i43_i_fu_199_p4 <= ip2checksum_V_data_V_dout(31 downto 24);
    p_Result_128_i46_i_fu_241_p4 <= ip2checksum_V_data_V_dout(47 downto 40);
    p_Result_128_i49_i_fu_273_p4 <= ip2checksum_V_data_V_dout(63 downto 56);
    p_Result_128_i52_i_fu_325_p4 <= ip2checksum_V_data_V_dout(79 downto 72);
    p_Result_128_i55_i_fu_357_p4 <= ip2checksum_V_data_V_dout(95 downto 88);
    p_Result_128_i58_i_fu_389_p4 <= ip2checksum_V_data_V_dout(111 downto 104);
    p_Result_128_i61_i_fu_421_p4 <= ip2checksum_V_data_V_dout(127 downto 120);
    p_Result_128_i64_i_fu_489_p4 <= ip2checksum_V_data_V_dout(143 downto 136);
    p_Result_128_i67_i_fu_521_p4 <= ip2checksum_V_data_V_dout(159 downto 152);
    p_Result_128_i70_i_fu_652_p4 <= r_V_fu_647_p2(15 downto 8);
    p_Result_128_i_i_fu_173_p4 <= ip2checksum_V_data_V_dout(15 downto 8);
    p_Result_s_fu_674_p5 <= (tmp_data_V_66_reg_707(511 downto 96) & checksum_V_fu_666_p3 & tmp_data_V_66_reg_707(79 downto 0));
    r_V_fu_647_p2 <= (ap_const_lv16_FFFF xor add_ln214_1_reg_725);
    tmp_nbreadreq_fu_126_p5 <= (0=>(ip2checksum_V_last_V_empty_n and ip2checksum_V_keep_V_empty_n and ip2checksum_V_data_V_empty_n), others=>'-');
    tmp_s_fu_569_p4 <= add_ln700_19_fu_563_p2(19 downto 16);
    trunc_ln647_29_fu_662_p1 <= r_V_fu_647_p2(8 - 1 downto 0);
    trunc_ln647_fu_183_p1 <= ip2checksum_V_data_V_dout(8 - 1 downto 0);

    tx_ip2crcFifo_V_data_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tx_ip2crcFifo_V_data_full_n, tmp_reg_703, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (tmp_reg_703 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tx_ip2crcFifo_V_data_blk_n <= tx_ip2crcFifo_V_data_full_n;
        else 
            tx_ip2crcFifo_V_data_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    tx_ip2crcFifo_V_data_din <= 
        p_Result_s_fu_674_p5 when (cics_firstWord(0) = '1') else 
        tmp_data_V_66_reg_707;

    tx_ip2crcFifo_V_data_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_703, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_703 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tx_ip2crcFifo_V_data_write <= ap_const_logic_1;
        else 
            tx_ip2crcFifo_V_data_write <= ap_const_logic_0;
        end if; 
    end process;


    tx_ip2crcFifo_V_keep_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tx_ip2crcFifo_V_keep_full_n, tmp_reg_703, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (tmp_reg_703 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tx_ip2crcFifo_V_keep_blk_n <= tx_ip2crcFifo_V_keep_full_n;
        else 
            tx_ip2crcFifo_V_keep_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    tx_ip2crcFifo_V_keep_din <= tmp_keep_V_reg_713;

    tx_ip2crcFifo_V_keep_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_703, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_703 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tx_ip2crcFifo_V_keep_write <= ap_const_logic_1;
        else 
            tx_ip2crcFifo_V_keep_write <= ap_const_logic_0;
        end if; 
    end process;


    tx_ip2crcFifo_V_last_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tx_ip2crcFifo_V_last_full_n, tmp_reg_703, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (tmp_reg_703 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tx_ip2crcFifo_V_last_blk_n <= tx_ip2crcFifo_V_last_full_n;
        else 
            tx_ip2crcFifo_V_last_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    tx_ip2crcFifo_V_last_din <= tmp_last_V_reg_718;

    tx_ip2crcFifo_V_last_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_703, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_703 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tx_ip2crcFifo_V_last_write <= ap_const_logic_1;
        else 
            tx_ip2crcFifo_V_last_write <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln1503_fu_579_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_569_p4),16));
    zext_ln647_1_fu_269_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(agg_result_V_0_1_i1_fu_261_p3),17));
    zext_ln647_2_fu_385_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(agg_result_V_0_1_i4_fu_377_p3),18));
    zext_ln647_3_fu_417_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(agg_result_V_0_1_i5_fu_409_p3),17));
    zext_ln647_4_fu_517_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(agg_result_V_0_1_i7_fu_509_p3),17));
    zext_ln647_fu_195_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(agg_result_V_0_1_i_i_fu_187_p3),17));
    zext_ln700_10_fu_549_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(agg_result_V_0_1_i8_fu_541_p3),17));
    zext_ln700_11_fu_559_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_18_fu_553_p2),20));
    zext_ln700_1_fu_237_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_fu_231_p2),18));
    zext_ln700_2_fu_301_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(agg_result_V_0_1_i2_fu_293_p3),17));
    zext_ln700_3_fu_311_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_12_fu_305_p2),18));
    zext_ln700_4_fu_321_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_13_fu_315_p2),19));
    zext_ln700_5_fu_353_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(agg_result_V_0_1_i3_fu_345_p3),19));
    zext_ln700_6_fu_449_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(agg_result_V_0_1_i6_fu_441_p3),17));
    zext_ln700_7_fu_465_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_15_fu_459_p2),18));
    zext_ln700_8_fu_475_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_16_fu_469_p2),19));
    zext_ln700_9_fu_485_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_17_fu_479_p2),20));
    zext_ln700_fu_227_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(agg_result_V_0_1_i_fu_219_p3),17));
end behav;
