-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity handle_read_requests is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rx_readRequestFifo_V_dout : IN STD_LOGIC_VECTOR (128 downto 0);
    rx_readRequestFifo_V_empty_n : IN STD_LOGIC;
    rx_readRequestFifo_V_read : OUT STD_LOGIC;
    rx_remoteMemCmd_V_din : OUT STD_LOGIC_VECTOR (112 downto 0);
    rx_remoteMemCmd_V_full_n : IN STD_LOGIC;
    rx_remoteMemCmd_V_write : OUT STD_LOGIC;
    rx_readEvenFifo_V_din : OUT STD_LOGIC_VECTOR (134 downto 0);
    rx_readEvenFifo_V_full_n : IN STD_LOGIC;
    rx_readEvenFifo_V_write : OUT STD_LOGIC );
end;


architecture behav of handle_read_requests is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv48_0 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_400 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000010000000000";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv48_400 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000010000000000";
    constant ap_const_lv32_FFFFFC00 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111110000000000";
    constant ap_const_lv113_0 : STD_LOGIC_VECTOR (112 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv24_1 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000001";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal hrr_fsmState_load_load_fu_266_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_nbreadreq_fu_98_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op9_read_state1 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal hrr_fsmState_load_reg_477 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_486 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op52_write_state2 : BOOLEAN;
    signal ap_predicate_op54_write_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal hrr_fsmState : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal request_vaddr_V : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    signal request_dma_length_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal request_qpn_V : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal request_psn_V : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal rx_readRequestFifo_V_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal rx_remoteMemCmd_V_blk_n : STD_LOGIC;
    signal rx_readEvenFifo_V_blk_n : STD_LOGIC;
    signal tmp_qpn_V_19_fu_278_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_qpn_V_19_reg_490 : STD_LOGIC_VECTOR (23 downto 0);
    signal readAddr_V_fu_288_p4 : STD_LOGIC_VECTOR (47 downto 0);
    signal readAddr_V_reg_495 : STD_LOGIC_VECTOR (47 downto 0);
    signal readLength_V_2_fu_299_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal readLength_V_2_reg_500 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_psn_V_6_reg_506 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_qpn_V_18_fu_346_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_qpn_V_18_reg_515 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_request_vaddr_V_new_s_phi_fu_129_p4 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln700_11_fu_326_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_reg_pp0_iter0_request_vaddr_V_new_s_reg_126 : STD_LOGIC_VECTOR (47 downto 0);
    signal icmp_ln895_3_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_request_dma_length_V_1_phi_fu_138_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln701_6_fu_333_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_request_dma_length_V_1_reg_135 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_request_vaddr_V_flag_phi_fu_147_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_request_vaddr_V_flag_reg_144 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_request_vaddr_V_new_1_phi_fu_158_p4 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln700_fu_362_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_reg_pp0_iter0_request_vaddr_V_new_1_reg_155 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_mux_request_dma_length_V_2_phi_fu_168_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln701_fu_369_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_request_dma_length_V_2_reg_165 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_request_vaddr_V_flag_1_phi_fu_178_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_request_vaddr_V_flag_1_reg_175 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_request_vaddr_V_new_2_phi_fu_193_p6 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_reg_pp0_iter0_request_vaddr_V_new_2_reg_190 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_phi_mux_request_dma_length_V_3_phi_fu_207_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_request_dma_length_V_3_reg_204 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_tmp_length_V_5_reg_218 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_tmp_length_V_5_reg_218 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_tmp_op_code_4_reg_229 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_reg_pp0_iter1_tmp_op_code_4_reg_229 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_reg_pp0_iter0_tmp_length_V_reg_242 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_tmp_length_V_reg_242 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter0_tmp_op_code_reg_253 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter1_tmp_op_code_reg_253 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_psn_V_fu_444_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_2_fu_417_p7 : STD_LOGIC_VECTOR (134 downto 0);
    signal tmp_3_fu_460_p7 : STD_LOGIC_VECTOR (134 downto 0);
    signal tmp_addr_V_fu_393_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_62_i_fu_396_p4 : STD_LOGIC_VECTOR (111 downto 0);
    signal sext_ln738_fu_432_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln738_fu_436_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_192 : BOOLEAN;
    signal ap_condition_100 : BOOLEAN;
    signal ap_condition_190 : BOOLEAN;
    signal ap_condition_159 : BOOLEAN;
    signal ap_condition_163 : BOOLEAN;
    signal ap_condition_87 : BOOLEAN;
    signal ap_condition_205 : BOOLEAN;
    signal ap_condition_239 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_tmp_length_V_5_reg_218_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_87)) then
                if ((ap_const_boolean_1 = ap_condition_163)) then 
                    ap_phi_reg_pp0_iter1_tmp_length_V_5_reg_218 <= rx_readRequestFifo_V_dout(103 downto 72);
                elsif ((ap_const_boolean_1 = ap_condition_159)) then 
                    ap_phi_reg_pp0_iter1_tmp_length_V_5_reg_218 <= ap_const_lv32_400;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_tmp_length_V_5_reg_218 <= ap_phi_reg_pp0_iter0_tmp_length_V_5_reg_218;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_tmp_length_V_reg_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_87)) then
                if (((icmp_ln895_fu_350_p2 = ap_const_lv1_0) and (hrr_fsmState_load_load_fu_266_p1 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_tmp_length_V_reg_242 <= request_dma_length_V;
                elsif (((icmp_ln895_fu_350_p2 = ap_const_lv1_1) and (hrr_fsmState_load_load_fu_266_p1 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_tmp_length_V_reg_242 <= ap_const_lv32_400;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_tmp_length_V_reg_242 <= ap_phi_reg_pp0_iter0_tmp_length_V_reg_242;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_tmp_op_code_4_reg_229_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_87)) then
                if ((ap_const_boolean_1 = ap_condition_163)) then 
                    ap_phi_reg_pp0_iter1_tmp_op_code_4_reg_229 <= ap_const_lv5_10;
                elsif ((ap_const_boolean_1 = ap_condition_159)) then 
                    ap_phi_reg_pp0_iter1_tmp_op_code_4_reg_229 <= ap_const_lv5_D;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_tmp_op_code_4_reg_229 <= ap_phi_reg_pp0_iter0_tmp_op_code_4_reg_229;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_tmp_op_code_reg_253_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_87)) then
                if (((icmp_ln895_fu_350_p2 = ap_const_lv1_0) and (hrr_fsmState_load_load_fu_266_p1 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_tmp_op_code_reg_253 <= ap_const_lv2_3;
                elsif (((icmp_ln895_fu_350_p2 = ap_const_lv1_1) and (hrr_fsmState_load_load_fu_266_p1 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_tmp_op_code_reg_253 <= ap_const_lv2_2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_tmp_op_code_reg_253 <= ap_phi_reg_pp0_iter0_tmp_op_code_reg_253;
                end if;
            end if; 
        end if;
    end process;

    hrr_fsmState_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_87)) then
                if (((icmp_ln895_fu_350_p2 = ap_const_lv1_0) and (hrr_fsmState_load_load_fu_266_p1 = ap_const_lv1_1))) then 
                    hrr_fsmState <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_condition_159)) then 
                    hrr_fsmState <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    request_psn_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_205)) then
                if ((hrr_fsmState_load_reg_477 = ap_const_lv1_1)) then 
                    request_psn_V <= tmp_psn_V_fu_444_p2;
                elsif (((tmp_reg_486 = ap_const_lv1_1) and (hrr_fsmState_load_reg_477 = ap_const_lv1_0))) then 
                    request_psn_V <= tmp_psn_V_6_reg_506;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                hrr_fsmState_load_reg_477 <= hrr_fsmState;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                readAddr_V_reg_495 <= rx_readRequestFifo_V_dout(71 downto 24);
                readLength_V_2_reg_500 <= rx_readRequestFifo_V_dout(103 downto 72);
                tmp_psn_V_6_reg_506 <= rx_readRequestFifo_V_dout(127 downto 104);
                tmp_qpn_V_18_reg_515 <= tmp_qpn_V_18_fu_346_p1;
                tmp_qpn_V_19_reg_490 <= tmp_qpn_V_19_fu_278_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_phi_mux_request_vaddr_V_flag_1_phi_fu_178_p6 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                request_dma_length_V <= ap_phi_mux_request_dma_length_V_3_phi_fu_207_p6;
                request_vaddr_V <= ap_phi_mux_request_vaddr_V_new_2_phi_fu_193_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                request_qpn_V <= tmp_qpn_V_19_fu_278_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (hrr_fsmState = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_reg_486 <= tmp_nbreadreq_fu_98_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln700_11_fu_326_p2 <= std_logic_vector(unsigned(readAddr_V_fu_288_p4) + unsigned(ap_const_lv48_400));
    add_ln700_fu_362_p2 <= std_logic_vector(unsigned(request_vaddr_V) + unsigned(ap_const_lv48_400));
    add_ln701_6_fu_333_p2 <= std_logic_vector(unsigned(readLength_V_2_fu_299_p4) + unsigned(ap_const_lv32_FFFFFC00));
    add_ln701_fu_369_p2 <= std_logic_vector(unsigned(request_dma_length_V) + unsigned(ap_const_lv32_FFFFFC00));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, rx_readRequestFifo_V_empty_n, ap_predicate_op9_read_state1, rx_remoteMemCmd_V_full_n, hrr_fsmState_load_reg_477, ap_predicate_op52_write_state2, rx_readEvenFifo_V_full_n, ap_predicate_op54_write_state2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((hrr_fsmState_load_reg_477 = ap_const_lv1_1) and (rx_readEvenFifo_V_full_n = ap_const_logic_0)) or ((rx_readEvenFifo_V_full_n = ap_const_logic_0) and (ap_predicate_op54_write_state2 = ap_const_boolean_1)) or ((rx_remoteMemCmd_V_full_n = ap_const_logic_0) and (ap_predicate_op52_write_state2 = ap_const_boolean_1)))) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((rx_readRequestFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, rx_readRequestFifo_V_empty_n, ap_predicate_op9_read_state1, rx_remoteMemCmd_V_full_n, hrr_fsmState_load_reg_477, ap_predicate_op52_write_state2, rx_readEvenFifo_V_full_n, ap_predicate_op54_write_state2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((hrr_fsmState_load_reg_477 = ap_const_lv1_1) and (rx_readEvenFifo_V_full_n = ap_const_logic_0)) or ((rx_readEvenFifo_V_full_n = ap_const_logic_0) and (ap_predicate_op54_write_state2 = ap_const_boolean_1)) or ((rx_remoteMemCmd_V_full_n = ap_const_logic_0) and (ap_predicate_op52_write_state2 = ap_const_boolean_1)))) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((rx_readRequestFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, rx_readRequestFifo_V_empty_n, ap_predicate_op9_read_state1, rx_remoteMemCmd_V_full_n, hrr_fsmState_load_reg_477, ap_predicate_op52_write_state2, rx_readEvenFifo_V_full_n, ap_predicate_op54_write_state2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((hrr_fsmState_load_reg_477 = ap_const_lv1_1) and (rx_readEvenFifo_V_full_n = ap_const_logic_0)) or ((rx_readEvenFifo_V_full_n = ap_const_logic_0) and (ap_predicate_op54_write_state2 = ap_const_boolean_1)) or ((rx_remoteMemCmd_V_full_n = ap_const_logic_0) and (ap_predicate_op52_write_state2 = ap_const_boolean_1)))) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((rx_readRequestFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, ap_done_reg, rx_readRequestFifo_V_empty_n, ap_predicate_op9_read_state1)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((rx_readRequestFifo_V_empty_n = ap_const_logic_0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(rx_remoteMemCmd_V_full_n, hrr_fsmState_load_reg_477, ap_predicate_op52_write_state2, rx_readEvenFifo_V_full_n, ap_predicate_op54_write_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((hrr_fsmState_load_reg_477 = ap_const_lv1_1) and (rx_readEvenFifo_V_full_n = ap_const_logic_0)) or ((rx_readEvenFifo_V_full_n = ap_const_logic_0) and (ap_predicate_op54_write_state2 = ap_const_boolean_1)) or ((rx_remoteMemCmd_V_full_n = ap_const_logic_0) and (ap_predicate_op52_write_state2 = ap_const_boolean_1)));
    end process;


    ap_condition_100_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0)
    begin
                ap_condition_100 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_159_assign_proc : process(tmp_nbreadreq_fu_98_p3, hrr_fsmState, icmp_ln895_3_fu_320_p2)
    begin
                ap_condition_159 <= ((icmp_ln895_3_fu_320_p2 = ap_const_lv1_1) and (tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0));
    end process;


    ap_condition_163_assign_proc : process(tmp_nbreadreq_fu_98_p3, hrr_fsmState, icmp_ln895_3_fu_320_p2)
    begin
                ap_condition_163 <= ((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (icmp_ln895_3_fu_320_p2 = ap_const_lv1_0) and (hrr_fsmState = ap_const_lv1_0));
    end process;


    ap_condition_190_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, hrr_fsmState_load_load_fu_266_p1, ap_block_pp0_stage0)
    begin
                ap_condition_190 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (hrr_fsmState_load_load_fu_266_p1 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_192_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_nbreadreq_fu_98_p3, hrr_fsmState, ap_block_pp0_stage0)
    begin
                ap_condition_192 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_205_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_205 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_239_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_01001)
    begin
                ap_condition_239 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_87_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_87 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_request_dma_length_V_1_phi_fu_138_p4_assign_proc : process(rx_readRequestFifo_V_dout, icmp_ln895_3_fu_320_p2, add_ln701_6_fu_333_p2, ap_phi_reg_pp0_iter0_request_dma_length_V_1_reg_135, ap_condition_192)
    begin
        if ((ap_const_boolean_1 = ap_condition_192)) then
            if ((icmp_ln895_3_fu_320_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_request_dma_length_V_1_phi_fu_138_p4 <= rx_readRequestFifo_V_dout(103 downto 72);
            elsif ((icmp_ln895_3_fu_320_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_request_dma_length_V_1_phi_fu_138_p4 <= add_ln701_6_fu_333_p2;
            else 
                ap_phi_mux_request_dma_length_V_1_phi_fu_138_p4 <= ap_phi_reg_pp0_iter0_request_dma_length_V_1_reg_135;
            end if;
        else 
            ap_phi_mux_request_dma_length_V_1_phi_fu_138_p4 <= ap_phi_reg_pp0_iter0_request_dma_length_V_1_reg_135;
        end if; 
    end process;


    ap_phi_mux_request_dma_length_V_2_phi_fu_168_p4_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, hrr_fsmState_load_load_fu_266_p1, ap_block_pp0_stage0, icmp_ln895_fu_350_p2, add_ln701_fu_369_p2, ap_phi_reg_pp0_iter0_request_dma_length_V_2_reg_165)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln895_fu_350_p2 = ap_const_lv1_1) and (hrr_fsmState_load_load_fu_266_p1 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_request_dma_length_V_2_phi_fu_168_p4 <= add_ln701_fu_369_p2;
        else 
            ap_phi_mux_request_dma_length_V_2_phi_fu_168_p4 <= ap_phi_reg_pp0_iter0_request_dma_length_V_2_reg_165;
        end if; 
    end process;


    ap_phi_mux_request_dma_length_V_3_phi_fu_207_p6_assign_proc : process(hrr_fsmState_load_load_fu_266_p1, tmp_nbreadreq_fu_98_p3, hrr_fsmState, ap_phi_mux_request_dma_length_V_1_phi_fu_138_p4, ap_phi_mux_request_dma_length_V_2_phi_fu_168_p4, ap_phi_reg_pp0_iter0_request_dma_length_V_3_reg_204, ap_condition_100)
    begin
        if ((ap_const_boolean_1 = ap_condition_100)) then
            if (((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0))) then 
                ap_phi_mux_request_dma_length_V_3_phi_fu_207_p6 <= ap_phi_mux_request_dma_length_V_1_phi_fu_138_p4;
            elsif ((hrr_fsmState_load_load_fu_266_p1 = ap_const_lv1_1)) then 
                ap_phi_mux_request_dma_length_V_3_phi_fu_207_p6 <= ap_phi_mux_request_dma_length_V_2_phi_fu_168_p4;
            else 
                ap_phi_mux_request_dma_length_V_3_phi_fu_207_p6 <= ap_phi_reg_pp0_iter0_request_dma_length_V_3_reg_204;
            end if;
        else 
            ap_phi_mux_request_dma_length_V_3_phi_fu_207_p6 <= ap_phi_reg_pp0_iter0_request_dma_length_V_3_reg_204;
        end if; 
    end process;


    ap_phi_mux_request_vaddr_V_flag_1_phi_fu_178_p6_assign_proc : process(hrr_fsmState_load_load_fu_266_p1, tmp_nbreadreq_fu_98_p3, hrr_fsmState, ap_phi_mux_request_vaddr_V_flag_phi_fu_147_p4, ap_phi_reg_pp0_iter0_request_vaddr_V_flag_1_reg_175, ap_condition_100)
    begin
        if ((ap_const_boolean_1 = ap_condition_100)) then
            if (((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_0) and (hrr_fsmState = ap_const_lv1_0))) then 
                ap_phi_mux_request_vaddr_V_flag_1_phi_fu_178_p6 <= ap_const_lv1_0;
            elsif (((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0))) then 
                ap_phi_mux_request_vaddr_V_flag_1_phi_fu_178_p6 <= ap_const_lv1_1;
            elsif ((hrr_fsmState_load_load_fu_266_p1 = ap_const_lv1_1)) then 
                ap_phi_mux_request_vaddr_V_flag_1_phi_fu_178_p6 <= ap_phi_mux_request_vaddr_V_flag_phi_fu_147_p4;
            else 
                ap_phi_mux_request_vaddr_V_flag_1_phi_fu_178_p6 <= ap_phi_reg_pp0_iter0_request_vaddr_V_flag_1_reg_175;
            end if;
        else 
            ap_phi_mux_request_vaddr_V_flag_1_phi_fu_178_p6 <= ap_phi_reg_pp0_iter0_request_vaddr_V_flag_1_reg_175;
        end if; 
    end process;


    ap_phi_mux_request_vaddr_V_flag_phi_fu_147_p4_assign_proc : process(ap_phi_reg_pp0_iter0_request_vaddr_V_flag_reg_144, icmp_ln895_fu_350_p2, ap_condition_190)
    begin
        if ((ap_const_boolean_1 = ap_condition_190)) then
            if ((icmp_ln895_fu_350_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_request_vaddr_V_flag_phi_fu_147_p4 <= ap_const_lv1_0;
            elsif ((icmp_ln895_fu_350_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_request_vaddr_V_flag_phi_fu_147_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_request_vaddr_V_flag_phi_fu_147_p4 <= ap_phi_reg_pp0_iter0_request_vaddr_V_flag_reg_144;
            end if;
        else 
            ap_phi_mux_request_vaddr_V_flag_phi_fu_147_p4 <= ap_phi_reg_pp0_iter0_request_vaddr_V_flag_reg_144;
        end if; 
    end process;


    ap_phi_mux_request_vaddr_V_new_1_phi_fu_158_p4_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, hrr_fsmState_load_load_fu_266_p1, ap_block_pp0_stage0, icmp_ln895_fu_350_p2, add_ln700_fu_362_p2, ap_phi_reg_pp0_iter0_request_vaddr_V_new_1_reg_155)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln895_fu_350_p2 = ap_const_lv1_1) and (hrr_fsmState_load_load_fu_266_p1 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_request_vaddr_V_new_1_phi_fu_158_p4 <= add_ln700_fu_362_p2;
        else 
            ap_phi_mux_request_vaddr_V_new_1_phi_fu_158_p4 <= ap_phi_reg_pp0_iter0_request_vaddr_V_new_1_reg_155;
        end if; 
    end process;


    ap_phi_mux_request_vaddr_V_new_2_phi_fu_193_p6_assign_proc : process(hrr_fsmState_load_load_fu_266_p1, tmp_nbreadreq_fu_98_p3, hrr_fsmState, ap_phi_mux_request_vaddr_V_new_s_phi_fu_129_p4, ap_phi_mux_request_vaddr_V_new_1_phi_fu_158_p4, ap_phi_reg_pp0_iter0_request_vaddr_V_new_2_reg_190, ap_condition_100)
    begin
        if ((ap_const_boolean_1 = ap_condition_100)) then
            if (((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0))) then 
                ap_phi_mux_request_vaddr_V_new_2_phi_fu_193_p6 <= ap_phi_mux_request_vaddr_V_new_s_phi_fu_129_p4;
            elsif ((hrr_fsmState_load_load_fu_266_p1 = ap_const_lv1_1)) then 
                ap_phi_mux_request_vaddr_V_new_2_phi_fu_193_p6 <= ap_phi_mux_request_vaddr_V_new_1_phi_fu_158_p4;
            else 
                ap_phi_mux_request_vaddr_V_new_2_phi_fu_193_p6 <= ap_phi_reg_pp0_iter0_request_vaddr_V_new_2_reg_190;
            end if;
        else 
            ap_phi_mux_request_vaddr_V_new_2_phi_fu_193_p6 <= ap_phi_reg_pp0_iter0_request_vaddr_V_new_2_reg_190;
        end if; 
    end process;


    ap_phi_mux_request_vaddr_V_new_s_phi_fu_129_p4_assign_proc : process(rx_readRequestFifo_V_dout, add_ln700_11_fu_326_p2, ap_phi_reg_pp0_iter0_request_vaddr_V_new_s_reg_126, icmp_ln895_3_fu_320_p2, ap_condition_192)
    begin
        if ((ap_const_boolean_1 = ap_condition_192)) then
            if ((icmp_ln895_3_fu_320_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_request_vaddr_V_new_s_phi_fu_129_p4 <= rx_readRequestFifo_V_dout(71 downto 24);
            elsif ((icmp_ln895_3_fu_320_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_request_vaddr_V_new_s_phi_fu_129_p4 <= add_ln700_11_fu_326_p2;
            else 
                ap_phi_mux_request_vaddr_V_new_s_phi_fu_129_p4 <= ap_phi_reg_pp0_iter0_request_vaddr_V_new_s_reg_126;
            end if;
        else 
            ap_phi_mux_request_vaddr_V_new_s_phi_fu_129_p4 <= ap_phi_reg_pp0_iter0_request_vaddr_V_new_s_reg_126;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_request_dma_length_V_1_reg_135 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_request_dma_length_V_2_reg_165 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_request_dma_length_V_3_reg_204 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_request_vaddr_V_flag_1_reg_175 <= "X";
    ap_phi_reg_pp0_iter0_request_vaddr_V_flag_reg_144 <= "X";
    ap_phi_reg_pp0_iter0_request_vaddr_V_new_1_reg_155 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_request_vaddr_V_new_2_reg_190 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_request_vaddr_V_new_s_reg_126 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tmp_length_V_5_reg_218 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tmp_length_V_reg_242 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tmp_op_code_4_reg_229 <= "XXXXX";
    ap_phi_reg_pp0_iter0_tmp_op_code_reg_253 <= "XX";

    ap_predicate_op52_write_state2_assign_proc : process(hrr_fsmState_load_reg_477, tmp_reg_486)
    begin
                ap_predicate_op52_write_state2 <= ((tmp_reg_486 = ap_const_lv1_1) and (hrr_fsmState_load_reg_477 = ap_const_lv1_0));
    end process;


    ap_predicate_op54_write_state2_assign_proc : process(hrr_fsmState_load_reg_477, tmp_reg_486)
    begin
                ap_predicate_op54_write_state2 <= ((tmp_reg_486 = ap_const_lv1_1) and (hrr_fsmState_load_reg_477 = ap_const_lv1_0));
    end process;


    ap_predicate_op9_read_state1_assign_proc : process(tmp_nbreadreq_fu_98_p3, hrr_fsmState)
    begin
                ap_predicate_op9_read_state1 <= ((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (hrr_fsmState = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    hrr_fsmState_load_load_fu_266_p1 <= hrr_fsmState;
    icmp_ln895_3_fu_320_p2 <= "1" when (unsigned(readLength_V_2_fu_299_p4) > unsigned(ap_const_lv32_400)) else "0";
    icmp_ln895_fu_350_p2 <= "1" when (unsigned(request_dma_length_V) > unsigned(ap_const_lv32_400)) else "0";
    readAddr_V_fu_288_p4 <= rx_readRequestFifo_V_dout(71 downto 24);
    readLength_V_2_fu_299_p4 <= rx_readRequestFifo_V_dout(103 downto 72);

    rx_readEvenFifo_V_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, hrr_fsmState_load_reg_477, rx_readEvenFifo_V_full_n, ap_predicate_op54_write_state2, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (hrr_fsmState_load_reg_477 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op54_write_state2 = ap_const_boolean_1)))) then 
            rx_readEvenFifo_V_blk_n <= rx_readEvenFifo_V_full_n;
        else 
            rx_readEvenFifo_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_readEvenFifo_V_din_assign_proc : process(hrr_fsmState_load_reg_477, ap_predicate_op54_write_state2, tmp_2_fu_417_p7, tmp_3_fu_460_p7, ap_condition_239)
    begin
        if ((ap_const_boolean_1 = ap_condition_239)) then
            if ((hrr_fsmState_load_reg_477 = ap_const_lv1_1)) then 
                rx_readEvenFifo_V_din <= tmp_3_fu_460_p7;
            elsif ((ap_predicate_op54_write_state2 = ap_const_boolean_1)) then 
                rx_readEvenFifo_V_din <= tmp_2_fu_417_p7;
            else 
                rx_readEvenFifo_V_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            rx_readEvenFifo_V_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    rx_readEvenFifo_V_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, hrr_fsmState_load_reg_477, ap_predicate_op54_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (hrr_fsmState_load_reg_477 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op54_write_state2 = ap_const_boolean_1)))) then 
            rx_readEvenFifo_V_write <= ap_const_logic_1;
        else 
            rx_readEvenFifo_V_write <= ap_const_logic_0;
        end if; 
    end process;


    rx_readRequestFifo_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, rx_readRequestFifo_V_empty_n, ap_predicate_op9_read_state1, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1))) then 
            rx_readRequestFifo_V_blk_n <= rx_readRequestFifo_V_empty_n;
        else 
            rx_readRequestFifo_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_readRequestFifo_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op9_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op9_read_state1 = ap_const_boolean_1))) then 
            rx_readRequestFifo_V_read <= ap_const_logic_1;
        else 
            rx_readRequestFifo_V_read <= ap_const_logic_0;
        end if; 
    end process;


    rx_remoteMemCmd_V_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rx_remoteMemCmd_V_full_n, ap_predicate_op52_write_state2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op52_write_state2 = ap_const_boolean_1))) then 
            rx_remoteMemCmd_V_blk_n <= rx_remoteMemCmd_V_full_n;
        else 
            rx_remoteMemCmd_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rx_remoteMemCmd_V_din <= (ap_const_lv113_0(112 downto 112) & tmp_62_i_fu_396_p4);

    rx_remoteMemCmd_V_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op52_write_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op52_write_state2 = ap_const_boolean_1))) then 
            rx_remoteMemCmd_V_write <= ap_const_logic_1;
        else 
            rx_remoteMemCmd_V_write <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln738_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ap_phi_reg_pp0_iter1_tmp_op_code_reg_253),4));

    tmp_2_fu_417_p7 <= (((((ap_const_lv2_1 & tmp_psn_V_6_reg_506) & ap_phi_reg_pp0_iter1_tmp_length_V_5_reg_218) & ap_const_lv48_0) & tmp_qpn_V_19_reg_490) & ap_phi_reg_pp0_iter1_tmp_op_code_4_reg_229);
    tmp_3_fu_460_p7 <= (((((ap_const_lv2_1 & tmp_psn_V_fu_444_p2) & ap_phi_reg_pp0_iter1_tmp_length_V_reg_242) & ap_const_lv48_0) & request_qpn_V) & zext_ln738_fu_436_p1);
    tmp_62_i_fu_396_p4 <= ((readLength_V_2_reg_500 & tmp_addr_V_fu_393_p1) & tmp_qpn_V_18_reg_515);
    tmp_addr_V_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(readAddr_V_reg_495),64));
    tmp_nbreadreq_fu_98_p3 <= (0=>(rx_readRequestFifo_V_empty_n), others=>'-');
    tmp_psn_V_fu_444_p2 <= std_logic_vector(unsigned(request_psn_V) + unsigned(ap_const_lv24_1));
    tmp_qpn_V_18_fu_346_p1 <= rx_readRequestFifo_V_dout(16 - 1 downto 0);
    tmp_qpn_V_19_fu_278_p1 <= rx_readRequestFifo_V_dout(24 - 1 downto 0);
    zext_ln738_fu_436_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln738_fu_432_p1),5));
end behav;
