-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rshiftWordByOctet_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rx_exh2aethShiftFifo_3_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    rx_exh2aethShiftFifo_3_empty_n : IN STD_LOGIC;
    rx_exh2aethShiftFifo_3_read : OUT STD_LOGIC;
    rx_exh2aethShiftFifo_5_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    rx_exh2aethShiftFifo_5_empty_n : IN STD_LOGIC;
    rx_exh2aethShiftFifo_5_read : OUT STD_LOGIC;
    rx_exh2aethShiftFifo_6_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    rx_exh2aethShiftFifo_6_empty_n : IN STD_LOGIC;
    rx_exh2aethShiftFifo_6_read : OUT STD_LOGIC;
    rx_aethSift2mergerFi_3_din : OUT STD_LOGIC_VECTOR (511 downto 0);
    rx_aethSift2mergerFi_3_full_n : IN STD_LOGIC;
    rx_aethSift2mergerFi_3_write : OUT STD_LOGIC;
    rx_aethSift2mergerFi_5_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    rx_aethSift2mergerFi_5_full_n : IN STD_LOGIC;
    rx_aethSift2mergerFi_5_write : OUT STD_LOGIC;
    rx_aethSift2mergerFi_6_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    rx_aethSift2mergerFi_6_full_n : IN STD_LOGIC;
    rx_aethSift2mergerFi_6_write : OUT STD_LOGIC );
end;


architecture behav of rshiftWordByOctet_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv60_0 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal io_acc_block_signal_op7 : STD_LOGIC;
    signal fsmState_2_load_load_fu_144_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_nbreadreq_fu_68_p5 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op7_read_state1 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal io_acc_block_signal_op39 : STD_LOGIC;
    signal fsmState_2_load_reg_261 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_265 : STD_LOGIC_VECTOR (0 downto 0);
    signal rs_firstWord_2_load_reg_285 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op39_write_state2 : BOOLEAN;
    signal io_acc_block_signal_op49 : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal fsmState_2 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal prevWord_data_V_18 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal prevWord_keep_V_17 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal rs_firstWord_2 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal rx_exh2aethShiftFifo_3_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal rx_exh2aethShiftFifo_5_blk_n : STD_LOGIC;
    signal rx_exh2aethShiftFifo_6_blk_n : STD_LOGIC;
    signal rx_aethSift2mergerFi_3_blk_n : STD_LOGIC;
    signal rx_aethSift2mergerFi_5_blk_n : STD_LOGIC;
    signal rx_aethSift2mergerFi_6_blk_n : STD_LOGIC;
    signal tmp_data_V_22_reg_269 : STD_LOGIC_VECTOR (511 downto 0);
    signal tmp_keep_V_22_reg_275 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_last_V_fu_156_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal rs_firstWord_2_load_load_fu_160_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_20_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_20_reg_289 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_p_0256_2_0_i_phi_fu_107_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0256_2_0_i_reg_104 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_rs_firstWord_4_new_0_phi_fu_118_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_rs_firstWord_4_new_0_reg_115 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_212_p3 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal p_Result_15_fu_243_p3 : STD_LOGIC_VECTOR (511 downto 0);
    signal p_Result_14_fu_224_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_16_fu_252_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_40_i_fu_164_p4 : STD_LOGIC_VECTOR (59 downto 0);
    signal trunc_ln647_fu_209_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_126_p4 : STD_LOGIC_VECTOR (479 downto 0);
    signal trunc_ln647_6_fu_221_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_135_p4 : STD_LOGIC_VECTOR (59 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_183 : BOOLEAN;
    signal ap_condition_170 : BOOLEAN;
    signal ap_condition_103 : BOOLEAN;
    signal ap_condition_193 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    fsmState_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_103)) then
                if ((fsmState_2_load_load_fu_144_p1 = ap_const_lv1_1)) then 
                    fsmState_2 <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_condition_170)) then 
                    fsmState_2 <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                fsmState_2_load_reg_261 <= fsmState_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_265 = ap_const_lv1_1) and (fsmState_2_load_reg_261 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                prevWord_data_V_18 <= tmp_data_V_22_reg_269;
                prevWord_keep_V_17 <= tmp_keep_V_22_reg_275;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_nbreadreq_fu_68_p5 = ap_const_lv1_1) and (fsmState_2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                rs_firstWord_2 <= ap_phi_mux_rs_firstWord_4_new_0_phi_fu_118_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_nbreadreq_fu_68_p5 = ap_const_lv1_1) and (fsmState_2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                rs_firstWord_2_load_reg_285 <= rs_firstWord_2;
                tmp_data_V_22_reg_269 <= rx_exh2aethShiftFifo_3_dout;
                tmp_keep_V_22_reg_275 <= rx_exh2aethShiftFifo_5_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_nbreadreq_fu_68_p5 = ap_const_lv1_1) and (rs_firstWord_2_load_load_fu_160_p1 = ap_const_lv1_0) and (fsmState_2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_last_V_20_reg_289 <= tmp_last_V_20_fu_174_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (fsmState_2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_reg_265 <= tmp_nbreadreq_fu_68_p5;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, io_acc_block_signal_op7, ap_predicate_op7_read_state1, io_acc_block_signal_op39, fsmState_2_load_reg_261, ap_predicate_op39_write_state2, io_acc_block_signal_op49)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((fsmState_2_load_reg_261 = ap_const_lv1_1) and (io_acc_block_signal_op49 = ap_const_logic_0)) or ((io_acc_block_signal_op39 = ap_const_logic_0) and (ap_predicate_op39_write_state2 = ap_const_boolean_1)))) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((io_acc_block_signal_op7 = ap_const_logic_0) and (ap_predicate_op7_read_state1 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, io_acc_block_signal_op7, ap_predicate_op7_read_state1, io_acc_block_signal_op39, fsmState_2_load_reg_261, ap_predicate_op39_write_state2, io_acc_block_signal_op49)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((fsmState_2_load_reg_261 = ap_const_lv1_1) and (io_acc_block_signal_op49 = ap_const_logic_0)) or ((io_acc_block_signal_op39 = ap_const_logic_0) and (ap_predicate_op39_write_state2 = ap_const_boolean_1)))) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((io_acc_block_signal_op7 = ap_const_logic_0) and (ap_predicate_op7_read_state1 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, io_acc_block_signal_op7, ap_predicate_op7_read_state1, io_acc_block_signal_op39, fsmState_2_load_reg_261, ap_predicate_op39_write_state2, io_acc_block_signal_op49)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((fsmState_2_load_reg_261 = ap_const_lv1_1) and (io_acc_block_signal_op49 = ap_const_logic_0)) or ((io_acc_block_signal_op39 = ap_const_logic_0) and (ap_predicate_op39_write_state2 = ap_const_boolean_1)))) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((io_acc_block_signal_op7 = ap_const_logic_0) and (ap_predicate_op7_read_state1 = ap_const_boolean_1)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, ap_done_reg, io_acc_block_signal_op7, ap_predicate_op7_read_state1)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((io_acc_block_signal_op7 = ap_const_logic_0) and (ap_predicate_op7_read_state1 = ap_const_boolean_1)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(io_acc_block_signal_op39, fsmState_2_load_reg_261, ap_predicate_op39_write_state2, io_acc_block_signal_op49)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((fsmState_2_load_reg_261 = ap_const_lv1_1) and (io_acc_block_signal_op49 = ap_const_logic_0)) or ((io_acc_block_signal_op39 = ap_const_logic_0) and (ap_predicate_op39_write_state2 = ap_const_boolean_1)));
    end process;


    ap_condition_103_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_103 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_170_assign_proc : process(tmp_nbreadreq_fu_68_p5, fsmState_2, tmp_last_V_fu_156_p1, ap_phi_mux_p_0256_2_0_i_phi_fu_107_p4)
    begin
                ap_condition_170 <= ((tmp_last_V_fu_156_p1 = ap_const_lv1_1) and (tmp_nbreadreq_fu_68_p5 = ap_const_lv1_1) and (ap_phi_mux_p_0256_2_0_i_phi_fu_107_p4 = ap_const_lv1_0) and (fsmState_2 = ap_const_lv1_0));
    end process;


    ap_condition_183_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_nbreadreq_fu_68_p5, fsmState_2, ap_block_pp0_stage0)
    begin
                ap_condition_183 <= ((tmp_nbreadreq_fu_68_p5 = ap_const_lv1_1) and (fsmState_2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0));
    end process;


    ap_condition_193_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_01001)
    begin
                ap_condition_193 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_p_0256_2_0_i_phi_fu_107_p4_assign_proc : process(rs_firstWord_2_load_load_fu_160_p1, tmp_last_V_20_fu_174_p2, ap_phi_reg_pp0_iter0_p_0256_2_0_i_reg_104, ap_condition_183)
    begin
        if ((ap_const_boolean_1 = ap_condition_183)) then
            if ((rs_firstWord_2_load_load_fu_160_p1 = ap_const_lv1_1)) then 
                ap_phi_mux_p_0256_2_0_i_phi_fu_107_p4 <= ap_const_lv1_0;
            elsif ((rs_firstWord_2_load_load_fu_160_p1 = ap_const_lv1_0)) then 
                ap_phi_mux_p_0256_2_0_i_phi_fu_107_p4 <= tmp_last_V_20_fu_174_p2;
            else 
                ap_phi_mux_p_0256_2_0_i_phi_fu_107_p4 <= ap_phi_reg_pp0_iter0_p_0256_2_0_i_reg_104;
            end if;
        else 
            ap_phi_mux_p_0256_2_0_i_phi_fu_107_p4 <= ap_phi_reg_pp0_iter0_p_0256_2_0_i_reg_104;
        end if; 
    end process;


    ap_phi_mux_rs_firstWord_4_new_0_phi_fu_118_p4_assign_proc : process(tmp_last_V_fu_156_p1, ap_phi_reg_pp0_iter0_rs_firstWord_4_new_0_reg_115, ap_condition_183)
    begin
        if ((ap_const_boolean_1 = ap_condition_183)) then
            if ((tmp_last_V_fu_156_p1 = ap_const_lv1_0)) then 
                ap_phi_mux_rs_firstWord_4_new_0_phi_fu_118_p4 <= ap_const_lv1_0;
            elsif ((tmp_last_V_fu_156_p1 = ap_const_lv1_1)) then 
                ap_phi_mux_rs_firstWord_4_new_0_phi_fu_118_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_rs_firstWord_4_new_0_phi_fu_118_p4 <= ap_phi_reg_pp0_iter0_rs_firstWord_4_new_0_reg_115;
            end if;
        else 
            ap_phi_mux_rs_firstWord_4_new_0_phi_fu_118_p4 <= ap_phi_reg_pp0_iter0_rs_firstWord_4_new_0_reg_115;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_p_0256_2_0_i_reg_104 <= "X";
    ap_phi_reg_pp0_iter0_rs_firstWord_4_new_0_reg_115 <= "X";

    ap_predicate_op39_write_state2_assign_proc : process(fsmState_2_load_reg_261, tmp_reg_265, rs_firstWord_2_load_reg_285)
    begin
                ap_predicate_op39_write_state2 <= ((tmp_reg_265 = ap_const_lv1_1) and (rs_firstWord_2_load_reg_285 = ap_const_lv1_0) and (fsmState_2_load_reg_261 = ap_const_lv1_0));
    end process;


    ap_predicate_op7_read_state1_assign_proc : process(tmp_nbreadreq_fu_68_p5, fsmState_2)
    begin
                ap_predicate_op7_read_state1 <= ((tmp_nbreadreq_fu_68_p5 = ap_const_lv1_1) and (fsmState_2 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    fsmState_2_load_load_fu_144_p1 <= fsmState_2;
    grp_fu_126_p4 <= prevWord_data_V_18(511 downto 32);
    grp_fu_135_p4 <= prevWord_keep_V_17(63 downto 4);
    io_acc_block_signal_op39 <= (rx_aethSift2mergerFi_6_full_n and rx_aethSift2mergerFi_5_full_n and rx_aethSift2mergerFi_3_full_n);
    io_acc_block_signal_op49 <= (rx_aethSift2mergerFi_6_full_n and rx_aethSift2mergerFi_5_full_n and rx_aethSift2mergerFi_3_full_n);
    io_acc_block_signal_op7 <= (rx_exh2aethShiftFifo_6_empty_n and rx_exh2aethShiftFifo_5_empty_n and rx_exh2aethShiftFifo_3_empty_n);
    p_Result_14_fu_224_p3 <= (trunc_ln647_6_fu_221_p1 & grp_fu_135_p4);
    p_Result_15_fu_243_p3 <= (ap_const_lv32_0 & grp_fu_126_p4);
    p_Result_16_fu_252_p3 <= (ap_const_lv4_0 & grp_fu_135_p4);
    p_Result_40_i_fu_164_p4 <= rx_exh2aethShiftFifo_5_dout(63 downto 4);
    p_Result_s_fu_212_p3 <= (trunc_ln647_fu_209_p1 & grp_fu_126_p4);
    rs_firstWord_2_load_load_fu_160_p1 <= rs_firstWord_2;

    rx_aethSift2mergerFi_3_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rx_aethSift2mergerFi_3_full_n, fsmState_2_load_reg_261, ap_predicate_op39_write_state2, ap_block_pp0_stage0)
    begin
        if ((((fsmState_2_load_reg_261 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op39_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            rx_aethSift2mergerFi_3_blk_n <= rx_aethSift2mergerFi_3_full_n;
        else 
            rx_aethSift2mergerFi_3_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_aethSift2mergerFi_3_din_assign_proc : process(fsmState_2_load_reg_261, ap_predicate_op39_write_state2, p_Result_s_fu_212_p3, p_Result_15_fu_243_p3, ap_condition_193)
    begin
        if ((ap_const_boolean_1 = ap_condition_193)) then
            if ((fsmState_2_load_reg_261 = ap_const_lv1_1)) then 
                rx_aethSift2mergerFi_3_din <= p_Result_15_fu_243_p3;
            elsif ((ap_predicate_op39_write_state2 = ap_const_boolean_1)) then 
                rx_aethSift2mergerFi_3_din <= p_Result_s_fu_212_p3;
            else 
                rx_aethSift2mergerFi_3_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            rx_aethSift2mergerFi_3_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    rx_aethSift2mergerFi_3_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, fsmState_2_load_reg_261, ap_predicate_op39_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (fsmState_2_load_reg_261 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op39_write_state2 = ap_const_boolean_1)))) then 
            rx_aethSift2mergerFi_3_write <= ap_const_logic_1;
        else 
            rx_aethSift2mergerFi_3_write <= ap_const_logic_0;
        end if; 
    end process;


    rx_aethSift2mergerFi_5_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rx_aethSift2mergerFi_5_full_n, fsmState_2_load_reg_261, ap_predicate_op39_write_state2, ap_block_pp0_stage0)
    begin
        if ((((fsmState_2_load_reg_261 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op39_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            rx_aethSift2mergerFi_5_blk_n <= rx_aethSift2mergerFi_5_full_n;
        else 
            rx_aethSift2mergerFi_5_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_aethSift2mergerFi_5_din_assign_proc : process(fsmState_2_load_reg_261, ap_predicate_op39_write_state2, p_Result_14_fu_224_p3, p_Result_16_fu_252_p3, ap_condition_193)
    begin
        if ((ap_const_boolean_1 = ap_condition_193)) then
            if ((fsmState_2_load_reg_261 = ap_const_lv1_1)) then 
                rx_aethSift2mergerFi_5_din <= p_Result_16_fu_252_p3;
            elsif ((ap_predicate_op39_write_state2 = ap_const_boolean_1)) then 
                rx_aethSift2mergerFi_5_din <= p_Result_14_fu_224_p3;
            else 
                rx_aethSift2mergerFi_5_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            rx_aethSift2mergerFi_5_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    rx_aethSift2mergerFi_5_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, fsmState_2_load_reg_261, ap_predicate_op39_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (fsmState_2_load_reg_261 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op39_write_state2 = ap_const_boolean_1)))) then 
            rx_aethSift2mergerFi_5_write <= ap_const_logic_1;
        else 
            rx_aethSift2mergerFi_5_write <= ap_const_logic_0;
        end if; 
    end process;


    rx_aethSift2mergerFi_6_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, rx_aethSift2mergerFi_6_full_n, fsmState_2_load_reg_261, ap_predicate_op39_write_state2, ap_block_pp0_stage0)
    begin
        if ((((fsmState_2_load_reg_261 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op39_write_state2 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            rx_aethSift2mergerFi_6_blk_n <= rx_aethSift2mergerFi_6_full_n;
        else 
            rx_aethSift2mergerFi_6_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_aethSift2mergerFi_6_din_assign_proc : process(fsmState_2_load_reg_261, ap_predicate_op39_write_state2, tmp_last_V_20_reg_289, ap_condition_193)
    begin
        if ((ap_const_boolean_1 = ap_condition_193)) then
            if ((fsmState_2_load_reg_261 = ap_const_lv1_1)) then 
                rx_aethSift2mergerFi_6_din <= ap_const_lv1_1;
            elsif ((ap_predicate_op39_write_state2 = ap_const_boolean_1)) then 
                rx_aethSift2mergerFi_6_din <= tmp_last_V_20_reg_289;
            else 
                rx_aethSift2mergerFi_6_din <= "X";
            end if;
        else 
            rx_aethSift2mergerFi_6_din <= "X";
        end if; 
    end process;


    rx_aethSift2mergerFi_6_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, fsmState_2_load_reg_261, ap_predicate_op39_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (fsmState_2_load_reg_261 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op39_write_state2 = ap_const_boolean_1)))) then 
            rx_aethSift2mergerFi_6_write <= ap_const_logic_1;
        else 
            rx_aethSift2mergerFi_6_write <= ap_const_logic_0;
        end if; 
    end process;


    rx_exh2aethShiftFifo_3_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, rx_exh2aethShiftFifo_3_empty_n, ap_predicate_op7_read_state1, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op7_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            rx_exh2aethShiftFifo_3_blk_n <= rx_exh2aethShiftFifo_3_empty_n;
        else 
            rx_exh2aethShiftFifo_3_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_exh2aethShiftFifo_3_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op7_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op7_read_state1 = ap_const_boolean_1))) then 
            rx_exh2aethShiftFifo_3_read <= ap_const_logic_1;
        else 
            rx_exh2aethShiftFifo_3_read <= ap_const_logic_0;
        end if; 
    end process;


    rx_exh2aethShiftFifo_5_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, rx_exh2aethShiftFifo_5_empty_n, ap_predicate_op7_read_state1, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op7_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            rx_exh2aethShiftFifo_5_blk_n <= rx_exh2aethShiftFifo_5_empty_n;
        else 
            rx_exh2aethShiftFifo_5_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_exh2aethShiftFifo_5_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op7_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op7_read_state1 = ap_const_boolean_1))) then 
            rx_exh2aethShiftFifo_5_read <= ap_const_logic_1;
        else 
            rx_exh2aethShiftFifo_5_read <= ap_const_logic_0;
        end if; 
    end process;


    rx_exh2aethShiftFifo_6_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, rx_exh2aethShiftFifo_6_empty_n, ap_predicate_op7_read_state1, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op7_read_state1 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            rx_exh2aethShiftFifo_6_blk_n <= rx_exh2aethShiftFifo_6_empty_n;
        else 
            rx_exh2aethShiftFifo_6_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    rx_exh2aethShiftFifo_6_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_predicate_op7_read_state1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op7_read_state1 = ap_const_boolean_1))) then 
            rx_exh2aethShiftFifo_6_read <= ap_const_logic_1;
        else 
            rx_exh2aethShiftFifo_6_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp_last_V_20_fu_174_p2 <= "1" when (p_Result_40_i_fu_164_p4 = ap_const_lv60_0) else "0";
    tmp_last_V_fu_156_p1 <= rx_exh2aethShiftFifo_6_dout;
    tmp_nbreadreq_fu_68_p5 <= (0=>(rx_exh2aethShiftFifo_6_empty_n and rx_exh2aethShiftFifo_5_empty_n and rx_exh2aethShiftFifo_3_empty_n), others=>'-');
    trunc_ln647_6_fu_221_p1 <= tmp_keep_V_22_reg_275(4 - 1 downto 0);
    trunc_ln647_fu_209_p1 <= tmp_data_V_22_reg_269(32 - 1 downto 0);
end behav;
